# Header
menu:
  home:
    url: /
  archives:
    url: /archives
  tags:
    url: /tags
  github:
    url: https://github.com/yscoder
    target: _blank
  weibo:
    url: http://www.weibo.com/ysweb
    target: _blank

rss: /atom.xml

#你的头像url
avatar: /img/logo.jpg

# email
email: 634206017@qq.com

# Content
tags:
  title: 标签

excerpt_link: more
mathjax: false
archive_yearly: true

#是否开启分享
share: true
#是否开启toc
#toc: false
toc:
  list_number: false  # 是否显示数字排序

# Miscellaneous
google_analytics: ''
favicon: /favicon.ico

# less
less:
  paths:
    - source/css/style.less


#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
duoshuo: ysblog
