# hexo-theme-indigo
# https://github.com/yscoder/hexo-theme-indigo
version: 1.1.10

#添加新菜单项遵循以下规则
# menu:
#  link:               fontawesome图标，省略前缀，本主题前缀为 icon-，必须
#    text: About       菜单显示的文字，如果省略即默认与图标一致，首字母会转大写
#    url: /about       链接，绝对或相对路径，必须。
#    target: _blank    是否跳出，省略则在当前页面打开
menu:
  home:
    text: 主页
    url: /
  archives:
    url: /archives
  tags:
    url: /tags
  th-list:
    text: Categories
    url: /categories
  github:
    url: https://github.com/yscoder
    target: _blank
  weibo:
    url: http://www.weibo.com/ysweb
    target: _blank
  link:
    text: 测试
    url: /custom

rss: /atom.xml

#你的头像url
avatar: //placekitten.com/200/200
#favicon
favicon: /favicon.ico

# email
email: 634206017@qq.com

# 设置 Android L Chrome 浏览器状态栏颜色
color: '#3F51B5'

# 页面标题
tags_title: Tags
archives_title: Archives
categories_title: Categories

# 文章截断
excerpt_render: false
excerpt_length: 200
excerpt_link: 阅读全文...
mathjax: false
archive_yearly: true

#是否开启分享
share: true

#是否开启打赏，关闭 reward: false
reward:
  title: 谢谢大爷~
  wechat: /img/wechat.jpg     #微信，关闭设为 false
  alipay: /img/alipay.jpg     #支付宝，关闭设为 false

#是否开启搜索
search: true

#是否大屏幕下文章页隐藏导航
hideMenu: true

#是否开启toc
#toc: false
toc:
  list_number: true  # 是否显示数字排序

#文章页版权声明内容，hexo中所有变量及辅助函数等均可调用，具体请查阅 hexo.io
copyright: 这里写留言或版权声明：<a href="<%- url_for(page.path).replace(/index\.html$/, '') %>" target="_blank" rel="external"><%- url.replace(/index\.html$/, '') %></a>

#站长统计，如要开启，输入CNZZ站点id，如 cnzz: 1255152447
cnzz: false

# Miscellaneous
google_analytics: false
google_site_verification: false

# less
less:
  compress: true
  paths:
    - source/css/style.less

# 是否开启多说评论，填写你在多说创建的站点二级域名
duoshuo: ysblog
# 使用 disqus 时关闭多说评论
disqus_shortname: false

# 规范网址
# 让搜索引擎重定向你的不同域名、不同子域、同域不同目录的站点到你期望的路径
# https://support.google.com/webmasters/answer/139066
# 假设配置为 canonical: http://imys.net，那么从搜索引擎中 www.imys.net 进入会重定向到 imys.net
canonical: false

# 版权起始年份
since_year: 2006

# 用户页面中作者相关的描述性文字，如不需要设为 false
about: 用户页面中作者相关的描述性文字，如不需要设为 false
